import React from 'react';
import {
  AbsoluteFill,
  Audio,
  OffthreadVideo,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  staticFile,
  Easing,
} from 'remotion';
import type { Action } from './types';

// Re-export Action type from shared module
export type { Action } from './types';

/**
 * Props injected from Root.tsx or passed at render time.
 * Override with --props flag: npx remotion render AgenticPPTVideo --props='{"layout":"9x16"}'
 */
export interface AgenticPPTProps {
  /** "16x9" or "9x16" */
  layout?: '16x9' | '9x16';
  /** Path to A-roll video in public/ folder */
  arollSrc?: string;
  /** Path to audio narration in public/ */
  audioSrc?: string;
  /** Slide components to render (imported dynamically) */
  slides?: React.FC[];
  /** Action timeline generated by AI */
  actions?: Action[];
}

// ============================================================
// DESIGN TOKENS (Sketch Notes style)
// ============================================================
const PAPER = '#f5f0e8';
const INK   = '#1a1a1a';
const GREY  = '#888';
const LIGHT_GREY = '#d0ccc4';
const TEAL  = '#4ECDC4';

// ============================================================
// DECORATION COMPONENTS
// ============================================================
const Halftone = () => (
  <div style={{
    position: 'absolute', inset: 0, opacity: 0.04, pointerEvents: 'none',
    backgroundImage: `radial-gradient(circle, ${INK} 1px, transparent 1px)`,
    backgroundSize: '6px 6px',
  }} />
);

const ComicBorder = () => (
  <>
    <div style={{position:'absolute',inset:18,border:`3.5px solid ${INK}`,borderRadius:2,pointerEvents:'none',zIndex:1}} />
    <div style={{position:'absolute',inset:14,border:`1px solid ${LIGHT_GREY}`,pointerEvents:'none',zIndex:1}} />
  </>
);

// ============================================================
// WHITEBOARD OVERLAY
// ============================================================
interface WhiteboardEntry {
  text: string;
  startTime: number;
  duration: number;
  visible: boolean;
}

const Whiteboard: React.FC<{ entries: WhiteboardEntry[]; currentTime: number }> = ({
  entries,
  currentTime,
}) => {
  const visible = entries.filter(
    e => e.visible && currentTime >= e.startTime && currentTime < e.startTime + e.duration
  );

  if (visible.length === 0) return null;

  return (
    <div style={{
      position: 'absolute',
      top: 20, right: 20,
      width: 320,
      background: '#fff',
      border: `2.5px solid ${INK}`,
      borderRadius: 4,
      padding: '16px 20px',
      boxShadow: `4px 4px 0 ${INK}`,
      zIndex: 80,
    }}>
      <div style={{
        fontFamily: "'Permanent Marker', cursive",
        fontSize: 13,
        color: GREY,
        letterSpacing: 1,
        marginBottom: 8,
      }}>
        WHITEBOARD
      </div>
      {visible.map((e, i) => {
        // Draw-in animation: 0.5s
        const progress = Math.min(1, (currentTime - e.startTime) / 0.5);
        return (
          <div key={i} style={{
            fontFamily: "'Caveat', cursive",
            fontSize: 22,
            fontWeight: 700,
            color: INK,
            lineHeight: 1.4,
            opacity: progress,
            transform: `translateY(${(1 - progress) * 8}px)`,
            marginBottom: 6,
          }}>
            {e.text}
          </div>
        );
      })}
    </div>
  );
};

// ============================================================
// SPOTLIGHT OVERLAY
// ============================================================
const Spotlight: React.FC<{ label: string; opacity: number }> = ({ label, opacity }) => (
  <div style={{
    position: 'absolute', inset: 0, zIndex: 60,
    background: `rgba(0,0,0,${0.5 * opacity})`,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    pointerEvents: 'none',
  }}>
    <div style={{
      background: TEAL,
      color: INK,
      fontFamily: "'Permanent Marker', cursive",
      fontSize: 24,
      padding: '10px 28px',
      borderRadius: 4,
      opacity,
    }}>
      ► {label}
    </div>
  </div>
);

// ============================================================
// SUBTITLE BAR
// ============================================================
const SubtitleBar: React.FC<{ text: string }> = ({ text }) => (
  <div style={{
    position: 'absolute', bottom: 0, left: 0, right: 0,
    padding: '14px 32px',
    background: PAPER, borderTop: `2.5px solid ${INK}`,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    minHeight: 60, zIndex: 100,
  }}>
    <div style={{
      fontFamily: "'Noto Sans SC', sans-serif",
      fontSize: 26, fontWeight: 500, color: text ? INK : 'transparent',
      textAlign: 'center', maxWidth: 900,
    }}>
      {text}
    </div>
  </div>
);

// ============================================================
// 16:9 LAYOUT  (A-roll left, Slide right)
// ============================================================
const Layout16x9: React.FC<{
  slideComponent: React.ReactNode;
  arollSrc: string;
  whiteboardEntries: WhiteboardEntry[];
  currentTime: number;
}> = ({ slideComponent, arollSrc, whiteboardEntries, currentTime }) => (
  <div style={{ position: 'absolute', inset: 0, display: 'flex' }}>
    {/* A-roll panel (22% width) */}
    <div style={{
      width: '22%', flexShrink: 0,
      border: `2.5px solid ${INK}`, borderRight: 'none',
      overflow: 'hidden',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      background: INK,
    }}>
      <OffthreadVideo
        src={staticFile(arollSrc)}
        style={{ width: '100%', height: 'auto', display: 'block' }}
      />
    </div>
    {/* Slide panel (74% width) */}
    <div style={{
      flex: 1,
      position: 'relative',
      overflow: 'hidden',
      border: `2.5px solid ${INK}`,
    }}>
      <AbsoluteFill style={{
        display: 'flex', flexDirection: 'column',
        justifyContent: 'center', alignItems: 'center',
        background: PAPER, padding: '48px 56px', textAlign: 'center',
      }}>
        <ComicBorder />
        {slideComponent}
      </AbsoluteFill>
      <Whiteboard entries={whiteboardEntries} currentTime={currentTime} />
    </div>
  </div>
);

// ============================================================
// 9:16 LAYOUT  (Slide fullscreen, A-roll PiP bottom-right)
// ============================================================
const Layout9x16: React.FC<{
  slideComponent: React.ReactNode;
  arollSrc: string;
  whiteboardEntries: WhiteboardEntry[];
  currentTime: number;
}> = ({ slideComponent, arollSrc, whiteboardEntries, currentTime }) => (
  <AbsoluteFill style={{
    display: 'flex', flexDirection: 'column',
    justifyContent: 'center', alignItems: 'center',
    background: PAPER, padding: '40px 32px', textAlign: 'center',
  }}>
    <ComicBorder />
    {slideComponent}
    {/* A-roll PiP */}
    <div style={{
      position: 'absolute',
      bottom: 80, right: 20,
      width: '26%',
      border: `2.5px solid ${INK}`,
      borderRadius: 4,
      overflow: 'hidden',
      boxShadow: `4px 4px 0 ${INK}`,
      zIndex: 50,
    }}>
      <OffthreadVideo
        src={staticFile(arollSrc)}
        style={{ width: '100%', height: 'auto', display: 'block' }}
      />
    </div>
    <Whiteboard entries={whiteboardEntries} currentTime={currentTime} />
  </AbsoluteFill>
);

// ============================================================
// PLACEHOLDER SLIDE (use until you add your own slides array)
// ============================================================
const PlaceholderSlide: React.FC<{ idx: number }> = ({ idx }) => (
  <div style={{
    fontFamily: "'Permanent Marker', cursive",
    fontSize: 48,
    color: INK,
    position: 'relative',
    zIndex: 5,
  }}>
    Slide {idx + 1}
  </div>
);

// ============================================================
// MAIN COMPOSITION
// ============================================================

/**
 * AgenticPPTVideo — A-roll + Slides + Whiteboard + Subtitles
 *
 * Usage:
 *   npx remotion render AgenticPPTVideo out/video.mp4
 *   npx remotion render AgenticPPTVideo-9x16 out/video-9x16.mp4
 *
 * Before rendering:
 *   cp /path/to/your-aroll.mp4 remotion-board/public/aroll.mp4
 *   cp /path/to/your-audio.m4a remotion-board/public/narration.m4a
 *   Edit ACTIONS below (or generate with scripts/generate-actions.md prompt)
 *
 * Action types (see types.ts for full definition):
 *   advance_slide — Switch to slide N at startTime seconds
 *   spotlight     — Highlight an element for a duration
 *   wb_write      — Draw whiteboard text
 *   wb_clear      — Clear the whiteboard
 *   subtitle      — Show subtitle text
 *   transition    — Animate slide entrance: 'fade' | 'slide-left' | 'slide-up'
 *   zoom          — Zoom into a target area with a given scale
 */
export const AgenticPPTVideo: React.FC<AgenticPPTProps> = ({
  layout = '16x9',
  arollSrc = 'aroll.mp4',
  audioSrc = 'narration.m4a',
  slides = [],
  actions = [],
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const t = frame / fps;

  // ── Determine current slide from advance_slide actions ──────
  let currentSlideIdx = 0;
  for (const a of actions) {
    if (a.type === 'advance_slide' && t >= a.startTime) {
      currentSlideIdx = a.slideIdx;
    }
  }

  const SlideComponent = slides[currentSlideIdx]
    ? slides[currentSlideIdx]
    : () => <PlaceholderSlide idx={currentSlideIdx} />;

  // ── Whiteboard entries (wb_write actions) ───────────────────
  const wbEntries: WhiteboardEntry[] = actions
    .filter(a => a.type === 'wb_write')
    .map(a => {
      const wa = a as { type: 'wb_write'; text: string; startTime: number; duration: number };
      return {
        text: wa.text,
        startTime: wa.startTime,
        duration: wa.duration,
        visible: t >= wa.startTime && t < wa.startTime + wa.duration,
      };
    });

  // ── Spotlight ───────────────────────────────────────────────
  const spotlightAction = actions.find(a =>
    a.type === 'spotlight' &&
    t >= (a as any).startTime &&
    t < (a as any).startTime + (a as any).duration
  ) as any;
  const spotlightOpacity = spotlightAction
    ? interpolate(t, [spotlightAction.startTime, spotlightAction.startTime + 0.3], [0, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })
    : 0;

  // ── Current subtitle ────────────────────────────────────────
  const subtitleAction = actions.find(a =>
    a.type === 'subtitle' &&
    t >= (a as any).startTime &&
    t < (a as any).startTime + (a as any).duration
  ) as any;
  const subtitleText = subtitleAction?.text ?? '';

  // ── Transition animation ────────────────────────────────────
  const transitionAction = actions.find(a =>
    a.type === 'transition' &&
    t >= a.startTime &&
    t < a.startTime + a.duration
  ) as Extract<Action, { type: 'transition' }> | undefined;

  let transitionStyle: React.CSSProperties = {};
  if (transitionAction) {
    const progress = interpolate(
      t,
      [transitionAction.startTime, transitionAction.startTime + transitionAction.duration],
      [0, 1],
      { extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic) }
    );
    switch (transitionAction.style) {
      case 'fade':
        transitionStyle = { opacity: progress };
        break;
      case 'slide-left':
        transitionStyle = { transform: `translateX(${(1 - progress) * 100}%)` };
        break;
      case 'slide-up':
        transitionStyle = { transform: `translateY(${(1 - progress) * 100}%)` };
        break;
    }
  }

  // ── Zoom animation ──────────────────────────────────────────
  const zoomAction = actions.find(a =>
    a.type === 'zoom' &&
    t >= a.startTime &&
    t < a.startTime + a.duration
  ) as Extract<Action, { type: 'zoom' }> | undefined;

  let zoomStyle: React.CSSProperties = {};
  if (zoomAction) {
    const half = zoomAction.duration / 2;
    const scale = t < zoomAction.startTime + half
      ? interpolate(
          t,
          [zoomAction.startTime, zoomAction.startTime + half],
          [1, zoomAction.scale],
          { extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic) }
        )
      : interpolate(
          t,
          [zoomAction.startTime + half, zoomAction.startTime + zoomAction.duration],
          [zoomAction.scale, 1],
          { extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.inOut(Easing.cubic) }
        );
    zoomStyle = { transform: `scale(${scale})` };
  }

  const slideNode = (
    <div style={{ ...transitionStyle, ...zoomStyle, width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <SlideComponent />
    </div>
  );

  return (
    <AbsoluteFill style={{ fontFamily: "'Noto Sans SC', sans-serif", backgroundColor: PAPER, color: INK }}>
      <Halftone />

      {layout === '16x9' ? (
        <Layout16x9
          slideComponent={slideNode}
          arollSrc={arollSrc}
          whiteboardEntries={wbEntries}
          currentTime={t}
        />
      ) : (
        <Layout9x16
          slideComponent={slideNode}
          arollSrc={arollSrc}
          whiteboardEntries={wbEntries}
          currentTime={t}
        />
      )}

      {spotlightAction && (
        <Spotlight label={spotlightAction.elementLabel} opacity={spotlightOpacity} />
      )}

      <SubtitleBar text={subtitleText} />

      {audioSrc && <Audio src={staticFile(audioSrc)} />}
    </AbsoluteFill>
  );
};

export default AgenticPPTVideo;
