// ============================================================
// SHARED ACTION TYPES
// Used by AgenticPPTVideo.tsx and TtsPPTVideo.tsx
// ============================================================

/**
 * A single action in the timeline.
 * Actions are generated by AI using the generate-actions prompt template.
 *
 * - advance_slide : Switch to a different slide at startTime
 * - spotlight     : Highlight an element label for a duration
 * - wb_write      : Draw text on the whiteboard overlay
 * - wb_clear      : Clear the whiteboard at startTime
 * - subtitle      : Show subtitle text for a duration
 * - transition    : Animate slide entrance (fade / slide-left / slide-up)
 * - zoom          : Zoom into a target area of the slide
 */
export type Action =
  | { type: 'advance_slide'; slideIdx: number; startTime: number }
  | { type: 'spotlight'; elementLabel: string; duration: number }
  | { type: 'wb_write'; text: string; startTime: number; duration: number }
  | { type: 'wb_clear'; startTime: number }
  | { type: 'subtitle'; text: string; startTime: number; duration: number }
  | { type: 'transition'; style: 'fade' | 'slide-left' | 'slide-up'; startTime: number; duration: number }
  | { type: 'zoom'; target: string; scale: number; startTime: number; duration: number };
